name: Delete Submodule Folder

on:
  workflow_dispatch: # 手动触发

jobs:
  delete-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的提交历史，以便可以访问子模块的提交

      - name: Delete submodule .git directory
        run: |
          # 假设子模块位于 'path/to/submodule'
          rm -rf TVBox-TV/.git

      - name: Remove submodule entry from .git/modules
        run: |
          # 删除子模块在 .git/modules 中的条目
          rm -rf .git/modules/TVBox-TV

      - name: Remove submodule entry from .git/config
        run: |
          # 从 .git/config 中删除子模块配置
          sed -i '/\[submodule "TVBox-TV"\]/,/}/d' .git/config

      - name: Commit changes
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Delete submodule folder and its .git directory"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUBXYTV_TOKEN }}
          branch: ${{ github.ref }}
