#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-armbian
# Description: Delete older releases and workflows runs
#==========================================================================

name: Delete older releases and workflows

on:
  schedule:
    - cron: '0 * * * *'
# 这里默认一小时执行一次
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Delete releases and workflows runs
        uses: xinyi1984/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: 2
          releases_keep_keyword: ""
          delete_workflows: true
          workflows_keep_day: 0
          workflows_keep_keyword: ""
          out_log: false
          gh_token: ${{ secrets.GITHUB_TOKEN }}
