name: Delete TVBox-TV Directory

on:
  workflow_dispatch: # 允许手动触发
  # 或者设置为定期运行，例如每天
  # schedule:
  #   - cron: '0 0 * * *' # 每天午夜触发

jobs:
  delete-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # 确保获取整个仓库历史
          fetch-depth: 0

      - name: Delete TVBox-TV Directory
        run: |
          # 检查 TVBox-TV 目录是否存在
          if [ -d "TVBox-TV" ]; then
            echo "Deleting TVBox-TV directory..."
            # 删除 TVBox-TV 目录
            rm -rf TVBox-TV
            # 将删除操作添加到暂存区
            git add TVBox-TV
            # 提交更改
            git commit -m "Delete TVBox-TV directory"
            # 推送更改到远程仓库
            git push
          else
            echo "TVBox-TV directory does not exist."
          fi

      - name: Check Git Status
        if: always() # 无论成功还是失败都执行
        run: |
          # 输出Git状态信息
          git status
