#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-armbian
# Description: Delete older releases and workflows runs
#==========================================================================

name: Delete older releases and workflows

on:
  schedule:
    - cron: '0/10 * * * *'
# 这里默认一小时执行一次

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete releases and workflows runs
        uses: xinyi1984/delete-releases-workflows@main
        with:
          delete_releases: "false"
          delete_tags: "false"
          releases_keep_latest: "90"
          releases_keep_keyword: ()
          delete_workflows: "false"
          workflows_keep_day: "90"
          workflows_keep_keyword: ()
          out_log: "false"
