name: Remove Commit History

on:
  workflow_dispatch:

jobs:
  remove-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      - name: Remove Commits
        run: |
          tag_commits=$(git for-each-ref --format='%(objectname)' refs/tags | grep -E '^20')
          if [ -n "$tag_commits" ]; then
            path_args=$(echo $tag_commits | tr ' ' '\n' | xargs -I {} git rev-parse --short {} | tr '\n' ' ')
            echo "Paths to filter: $path_args"
            git filter-repo --invert-paths --path $path_args
            git push origin --force
          else
            echo "No commits associated with '20' prefixed tags found."
          fi
