#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-armbian
# Description: Delete older releases and workflows runs
#==========================================================================

name: Delete older releases and workflows

on:
  schedule:
    - cron: '0/10 * * * *'
# 这里默认一小时执行一次

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete releases and workflows runs
        uses: xinyi1984/delete-releases-workflows@main
        with:
          required: "true"
          del_releases: "true"
          releases_keep_latest: 1
          del_workflows: "true"
          workflows_keep_day: 0
          gh_token: ${{ secrets.GITHUB_TOKEN }}
