name: Delete TVBox-TV Directory

on:
  schedule:
    - cron: '0 */4 * * *'
# 这里默认间隔4小时执行一次

  workflow_dispatch:

jobs:
  delete-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git User Info
        run: |
          git config --global user.name "xinyi1984"
          git config --global user.email "75725458@qq.com"

      - name: Check if TVBox-TV Directory Exists and Delete It
        run: |
          if [ -d "TVBox-TV" ]; then
            echo "Deleting TVBox-TV directory..."
            rm -rf TVBox-TV
            git add TVBox-TV
            git commit -m "Delete TVBox-TV directory"
            git push
          else
            echo "TVBox-TV directory does not exist."
          fi
