name: Delete Tags

on:
  schedule:
    - cron: '0 */4 * * *'
  # 这里默认间隔4小时执行一次
  workflow_dispatch:

jobs:
  delete-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git User Info
        run: |
          git config --global user.name "xinyi1984"
          git config --global user.email "75725458@qq.com"

      - name: Rewrite History
        run: |
          # 获取与已删除标签相关的提交哈希
          tag_commits=$(git for-each-ref --format='%(objectname)' refs/tags | grep -E "$(echo $tags_to_delete | tr ' ' '|')")
          if [ -n "$tag_commits" ]; then
            # 使用 git filter-repo 移除这些提交
            git filter-repo --invert-paths --path $(echo $tag_commits | tr ' ' '\n' | xargs -I {} git rev-parse --short {} | tr '\n' ' ')
            # 强制推送重写后的历史到远程仓库
            git push origin --force
          else
            echo "No commits associated with deleted tags found."
          fi
