name: Delete Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the branch to delete'
        required: true
        default: 'feature-branch'

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          # 设置你的 GitHub 访问令牌
          # 警告：不要在代码中硬编码令牌，使用仓库的 secrets 更安全
          TOKEN=${{ secrets.GITHUBXYTV_TOKEN }}
          
          # 获取工作流触发时输入的分支名
          BRANCH_NAME=${{ github.event.inputs.branch_name }}
          
          # 使用 GitHub API 删除分支
          curl -X DELETE \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches/$BRANCH_NAME"
